version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:5.1.2
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
  image: confluentinc/cp-enterprise-kafka:5.1.2
  ports:
    - "9092:9092"
  environment:
    KAFKA_BROKER_ID: 1
    KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://ec2-107-21-137-193.compute-1.amazonaws.com:9092
    KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  node-app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - kafka
    environment:
      KAFKA_BROKER: kafka:9092
